### ISSUE TITLE
zstring_rtrim (and others) do not respect isspace()

### ISSUE THREAD

**Issue by msemtd** [fnoyanisi/zString#1]
zstring_rtrim is documented as "Trims trailing white-space characters" but only removes space characters rather than anything that is true for isspace()

**Comment by fnoyanisi** [comment]
While writing these functions, my expectation was to remove only the space character, i.e. ASCII code 32, as opposed to all characters recognized as _white space_ by isspace(). 

I have had a similar feedback from someone in stackoverflow, and this makes me to consider amending the code so that all characters given below will be removed

' '   (0x20)    space (SPC)
'\t'    (0x09)  horizontal tab (TAB)
'\n'    (0x0a)  newline (LF)
'\v'    (0x0b)  vertical tab (VT)
'\f'    (0x0c)  feed (FF)
'\r'    (0x0d)  carriage return (CR)

Thanks for the feedback!

**Comment by fnoyanisi** [comment]
@msemtd , code has been updated.... trim family functions are all compatible with isspace(3).
